services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitfi-backend
    env_file:
      - .env
      - secret.env
    environment:
      - MONGOOSE_URI=mongodb://mongo:27017/fitfi
      - REDIS_URI=redis://redis:6379
    ports:
      - 3000:3000
  redis:
    image: redis:latest
    container_name: fitfi-redis
    volumes:
      - redis_data:/data
  mongo:
    image: mongo:latest
    container_name: fitfi-mongo
    volumes:
      - mongo_data:/data/db
  backend-docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    container_name: fitfi-backend-docs
    ports:
      - 3001:3001

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
