services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitfi-backend
    env_file:
      - .evn
      - secret.env
    ports:
      - 3000:3000
  redis:
    image: redis:latest
    container_name: fitfi-redis
    ports:
      - 6378:6379
    volumes:
      - redis_data:/data
  mongo:
    image: mongo:latest
    container_name: fitfi-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  backend-docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    container_name: fitfi-backend-docs
    ports:
      - 3001:3001

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
